routes/web.php
<?php

use App\Http\Controllers\AdminSettingController;
use App\Http\Controllers\BranchController;
use App\Http\Controllers\CityController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\CourierController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DesignationController;
use App\Http\Controllers\DropdownController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RouteController;
use App\Http\Controllers\StateController;
use App\Models\Customer;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RPOController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\StockController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ShelveController;
use App\Http\Controllers\ShelvelocationController;
use App\Http\Controllers\ShipmentController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\ZoneController;
use App\Models\Country;
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth'])->group(function () {

    Route::get('/', function () {
        return view('layout.main');
    });

    Route::resource('customers',CustomerController::class);

    Route::get('/test',[DropdownController::class,'index']);
        Route::resource('stocks', StockController::class);
        Route::resource('users', UserController::class);
        Route::post('post',[UserController::class,'Test']);
        Route::resource('branches',BranchController::class);
        Route::resource('routes',RouteController::class);
        Route::resource('countries',CountryController::class);
        Route::resource('states',StateController::class);
        Route::resource('cities',CityController::class);
        Route::resource('couriers',CourierController::class);
        Route::resource('roles', RoleController::class);
        Route::get('dependent-dropdown', [DropdownController::class, 'index']);
    Route::post('api/fetch-states', [DropdownController::class, 'fetchState']);
    Route::post('api/fetch-cities', [DropdownController::class, 'fetchCity']);


    Route::resource('designations', DesignationController::class);

    Route::resource('suppliers', SupplierController::class);

    Route::resource('shelvelocations',ShelvelocationController::class);

    Route::resource('shelves',ShelveController::class);


    Route::resource('products',ProductController::class);

    Route::resource('zones',ZoneController::class);
    Route::get('addcityzone',[ZoneController::class,'addcityzone']);

    Route::get('addcountryzone',[ZoneController::class,'addcountryzone']);


    Route::resource('RPO', RPOController::class);
    Route::get('RPO_pendings', [RPOController::class,'RPO_PENDINGS']);

    Route::get('/RPO_print/{id}', [RPOController::class,'RPO_PRINT']);
    Route::get('/RPO_detail/{id}', [RPOController::class,'RPO_detail']);
    Route::get('/RPO_status_update/{id}', [RPOController::class,'RPO_status_update']);
    // Route::post('/rpo_status_updated', [RPOController::class, 'RPO_status_updated']);
    Route::put('rpo_status_updated/{id}', [RPOController::class, 'RPO_status_updated']);
    Route::get('/rpo.create', [RPOController::class,'rpo_create']);
    Route::get('/RPO_delete/{id}', [RPOController::class,'RPO_delete']);

    Route::post('/rpo_search', [RPOController::class,'RPO_search']);
  
    // settings 
    Route::get('/settings.main', [AdminSettingController::class,'index']);
    Route::get('/settings.social', [AdminSettingController::class,'SettingSocial']);
    Route::get('/settings.smtpconfig', [AdminSettingController::class,'Smtp_config']);
    Route::get('/settings.paymentsetting', [AdminSettingController::class,'paymentsetting']);
    Route::get('/settings.testimonials', [AdminSettingController::class,'testimonials']);
    Route::get('/testimonial.create', [AdminSettingController::class,'testimonial_create']);
    
    Route::post('/  mainsettings.applychanges', [AdminSettingController::class,'applychanges']);
    Route::post('/mainsettings.applySocialchanges', [AdminSettingController::class,'applySocialchanges']);
    Route::post('/mainsettings.Smtp_config_update', [AdminSettingController::class,'Smtp_config_update']);
    Route::post('/mainsettings.paymentsettingUpdate', [AdminSettingController::class,'paymentsettingUpdate']);
    Route::post('/mainsettings.testimonial.create', [AdminSettingController::class,'testimonialStore']);
    Route::post('/mainsettings.testimonial.updated', [AdminSettingController::class,'testimonial_updated']);
    

    Route::get('/testimonial_delete/{id}', [AdminSettingController::class,'testimonial_delete']);
    Route::get('/testimonial_update_page/{id}', [AdminSettingController::class, 'testimonial_update_page']);
    
    

    // Shipment 
    Route::get('/shipments.main', [ShipmentController::class,'index']);
    Route::get('/shipments.create', [ShipmentController::class,'ship_create']);
    Route::post('/shipments.store', [ShipmentController::class,'shipment_store']);
    Route::get('/shipment_update/{id}', [ShipmentController::class,'shipment_update']);
    Route::post('/shipments.updated', [ShipmentController::class,'shipments_updated']);
    Route::get('/shipment_delete/{id}', [ShipmentController::class,'shipment_delete']);
    Route::get('/shipments.return_to_client', [ShipmentController::class,'return_to_client']);
    Route::get('/shipments.delivered_shipments', [ShipmentController::class,'delivered_shipments']);
    Route::get('/shipments.add_shipment', [ShipmentController::class,'ship_create']);
    Route::get('/shipments.deleted_shipments', [ShipmentController::class,'deleted_shipments']);
    Route::get('/shipment_delete_restore/{id}', [ShipmentController::class,'shipment_delete_restore']);
    Route::get('/shipment_delete_permanent/{id}', [ShipmentController::class,'delete_permanent']);
    Route::get('/shipments.inTransit_shipments', [ShipmentController::class,'inTransit_shipments']);
    Route::post('/shipment_search', [ShipmentController::class,'shipment_search']);
    
    Route::get('export', [ShipmentController::class, 'export'])->name('export');
    Route::post('import', [ShipmentController::class, 'import'])->name('import');

    
    Route::get('/shipments.import_shipments', [ShipmentController::class,'import_shipments']);
    Route::get('/shipments.export_shipments', [ShipmentController::class,'export_shipments']);
    Route::get('/shipment_archive/{id}', [ShipmentController::class,'shipment_archive']);
    Route::get('/shipment_De_archive/{id}', [ShipmentController::class,'shipment_De_archive']);
    Route::get('/shipments.archive_shipments', [ShipmentController::class,'archive_shipments']);

    Route::get('/shipment_delete_from_search/{id}', [ShipmentController::class,'shipment_delete_from_search']);
    Route::get('/shipment_archive_from_search/{id}', [ShipmentController::class,'shipment_archive_from_search']);
    Route::get('/shipments.print_shipments', [ShipmentController::class,'print_shipments']);

    Route::post('/shipments.bulk_print', [ShipmentController::class,'bulk_print']);
    
    
    // mainsettings.applySocialchanges
    // rpo.store

    // RPO_detail
    // ->route('RPO.pendings');
    

});

app/Models/Stock.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Stock extends Model
{
    use HasFactory;
    public $fillable = [
        'product_name',
        'product_desc',
        'product_qty'
    ];
}

app/Http/Controllers/StockController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Stock;

class StockController extends Controller
{
    public function index()
    {
        $stocks = Stock::latest()->paginate(5);
        return view('stocks.index',compact('stocks'))->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function create()
    {
        return view('stocks.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'product_name' => 'required',
            'product_desc' => 'required',
            'product_qty' => 'required',
        ]);

        Stock::create($request->all());
        return redirect()->route('stocks.index')->with('success','Created Successfully.');
    }

    public function show(Stock $stock)
    {
        return view('stocks.show',compact('stock'));
    }


    public function edit(Stock $stock)
    {
        return view('stocks.edit',compact('stock'));
    }

    public function update(Request $request, Stock $stock)
    {
        $request->validate([
            'product_name' => 'required',
            'product_desc' => 'required',
            'product_qty' => 'required',
        ]);

        $stock->update($request->all());
        return redirect()->route('stocks.index')->with('success','Updated Successfully.');
    }


    public function destroy(Stock $stock)
    {
        $stock->delete();
        return redirect()->route('stocks.index')->with('success','Student deleted successfully.');
    }
}

resources/views/stocks/create.blade.php
@extends('layout.main')

@section('content')

<div class="row">
    <div class="col-lg-12">
        <h2 class="text-center">Add Stock</h2>
    </div>
    <div class="col-lg-12 text-center" style="margin-top:10px;margin-bottom: 10px;">
        <a class="btn btn-primary" href="{{ route('stocks.index') }}"> Back</a>
    </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Oops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<form action="{{ route('stocks.store') }}" method="POST">
    @csrf

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Product Name:</strong>
                <input type="text" name="product_name" class="form-control" placeholder="Product Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Product Description:</strong>
                <textarea class="form-control" style="height:150px" name="product_desc" placeholder="Product Description"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Qty:</strong>
                <input type="number" class="form-control" name="product_qty" placeholder="Quantity">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

</form>
@endsection

resources/views/stocks/edit.blade.php
@extends('layout.main')
@section('content')

    <div class="row">
        <div class="col-lg-12">
            <h2 class="text-center">Edit Stock</h2>
        </div>
        <div class="col-lg-12 text-center" style="margin-top:10px;margin-bottom: 10px;">
            <a class="btn btn-primary" href="{{ route('stocks.index') }}"> Back</a>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('stocks.update',$stock->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Product Name:</strong>
                    <input type="text" name="product_name" value="{{ $stock->product_name }}" class="form-control" placeholder="Product Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Product Description:</strong>
                    <textarea class="form-control" name="product_desc" style="height:150px"  placeholder="Product Description">{{ $stock->product_desc }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Qty:</strong>
                    <input type="number" name="product_qty" class="form-control" style="height:150px" value="{{ $stock->product_qty }}"  placeholder="Quantity">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

resources/views/stocks/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="row">
        <div class="col-lg-12">
            <h2 class="text-center">Simple Stock Management Application | BH</h2>
        </div>
        <div class="col-lg-12 text-center" style="margin-top:10px;margin-bottom: 10px;">
            <a class="btn btn-success " href="{{ route('stocks.create') }}"> Add Stock</a>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            {{ $message }}
        </div>
    @endif

    @if(sizeof($stocks) > 0)
        <table class="table table-bordered">
            <tr>
                <th>No</th>
                <th>Product Name</th>
                <th>Product Description</th>
                <th>Qty.</th>
                <th width="280px">More</th>
            </tr>
            @foreach ($stocks as $stock)
                <tr>
                    <td>{{ ++$i }}</td>
                    <td>{{ $stock->product_name }}</td>
                    <td>{{ $stock->product_desc }}</td>
                    <td>{{ $stock->product_qty }}</td>
                    <td>
                        <form action="{{ route('stocks.destroy',$stock->id) }}" method="POST">
                            <a class="btn btn-info" href="{{ route('stocks.show',$stock->id) }}">Show</a>
                            <a class="btn btn-primary" href="{{ route('stocks.edit',$stock->id) }}">Edit</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>
    @else
        <div class="alert alert-alert">Start Adding to the Database.</div>
    @endif

    {!! $stocks->links() !!}

@endsection

resources/views/stocks/show.blade.php
@extends('layout.main')
@extends('stocks.layout')

@section('content')

    <div class="row">
        <div class="col-lg-12">
            <h2 class="text-center">Show Stock</h2>
        </div>
        <div class="col-lg-12 text-center" style="margin-top:10px;margin-bottom: 10px;">
            <a class="btn btn-primary" href="{{ route('stocks.index') }}"> Back</a>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Product Name : </strong>
                {{ $stock->product_name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Product Description : </strong>
                {{ $stock->product_desc }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Quantity : </strong>
                {{ $stock->product_qty }}
            </div>
        </div>
    </div>
@endsection