routes/web.php
<?php

use App\Http\Controllers\AdminSettingController;
use App\Http\Controllers\BranchController;
use App\Http\Controllers\CityController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\CourierController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DesignationController;
use App\Http\Controllers\DropdownController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RouteController;
use App\Http\Controllers\StateController;
use App\Models\Customer;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RPOController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\StockController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ShelveController;
use App\Http\Controllers\ShelvelocationController;
use App\Http\Controllers\ShipmentController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\ZoneController;
use App\Models\Country;
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth'])->group(function () {

    Route::get('/', function () {
        return view('layout.main');
    });

    Route::resource('customers',CustomerController::class);

    Route::get('/test',[DropdownController::class,'index']);
        Route::resource('stocks', StockController::class);
        Route::resource('users', UserController::class);
        Route::post('post',[UserController::class,'Test']);
        Route::resource('branches',BranchController::class);
        Route::resource('routes',RouteController::class);
        Route::resource('countries',CountryController::class);
        Route::resource('states',StateController::class);
        Route::resource('cities',CityController::class);
        Route::resource('couriers',CourierController::class);
        Route::resource('roles', RoleController::class);
        Route::get('dependent-dropdown', [DropdownController::class, 'index']);
    Route::post('api/fetch-states', [DropdownController::class, 'fetchState']);
    Route::post('api/fetch-cities', [DropdownController::class, 'fetchCity']);


    Route::resource('designations', DesignationController::class);

    Route::resource('suppliers', SupplierController::class);

    Route::resource('shelvelocations',ShelvelocationController::class);

    Route::resource('shelves',ShelveController::class);


    Route::resource('products',ProductController::class);

    Route::resource('zones',ZoneController::class);
    Route::get('addcityzone',[ZoneController::class,'addcityzone']);

    Route::get('addcountryzone',[ZoneController::class,'addcountryzone']);


    Route::resource('RPO', RPOController::class);
    Route::get('RPO_pendings', [RPOController::class,'RPO_PENDINGS']);

    Route::get('/RPO_print/{id}', [RPOController::class,'RPO_PRINT']);
    Route::get('/RPO_detail/{id}', [RPOController::class,'RPO_detail']);
    Route::get('/RPO_status_update/{id}', [RPOController::class,'RPO_status_update']);
    // Route::post('/rpo_status_updated', [RPOController::class, 'RPO_status_updated']);
    Route::put('rpo_status_updated/{id}', [RPOController::class, 'RPO_status_updated']);
    Route::get('/rpo.create', [RPOController::class,'rpo_create']);
    Route::get('/RPO_delete/{id}', [RPOController::class,'RPO_delete']);

    Route::post('/rpo_search', [RPOController::class,'RPO_search']);
  
    // settings 
    Route::get('/settings.main', [AdminSettingController::class,'index']);
    Route::get('/settings.social', [AdminSettingController::class,'SettingSocial']);
    Route::get('/settings.smtpconfig', [AdminSettingController::class,'Smtp_config']);
    Route::get('/settings.paymentsetting', [AdminSettingController::class,'paymentsetting']);
    Route::get('/settings.testimonials', [AdminSettingController::class,'testimonials']);
    Route::get('/testimonial.create', [AdminSettingController::class,'testimonial_create']);
    
    Route::post('/  mainsettings.applychanges', [AdminSettingController::class,'applychanges']);
    Route::post('/mainsettings.applySocialchanges', [AdminSettingController::class,'applySocialchanges']);
    Route::post('/mainsettings.Smtp_config_update', [AdminSettingController::class,'Smtp_config_update']);
    Route::post('/mainsettings.paymentsettingUpdate', [AdminSettingController::class,'paymentsettingUpdate']);
    Route::post('/mainsettings.testimonial.create', [AdminSettingController::class,'testimonialStore']);
    Route::post('/mainsettings.testimonial.updated', [AdminSettingController::class,'testimonial_updated']);
    

    Route::get('/testimonial_delete/{id}', [AdminSettingController::class,'testimonial_delete']);
    Route::get('/testimonial_update_page/{id}', [AdminSettingController::class, 'testimonial_update_page']);
    
    

    // Shipment 
    Route::get('/shipments.main', [ShipmentController::class,'index']);
    Route::get('/shipments.create', [ShipmentController::class,'ship_create']);
    Route::post('/shipments.store', [ShipmentController::class,'shipment_store']);
    Route::get('/shipment_update/{id}', [ShipmentController::class,'shipment_update']);
    Route::post('/shipments.updated', [ShipmentController::class,'shipments_updated']);
    Route::get('/shipment_delete/{id}', [ShipmentController::class,'shipment_delete']);
    Route::get('/shipments.return_to_client', [ShipmentController::class,'return_to_client']);
    Route::get('/shipments.delivered_shipments', [ShipmentController::class,'delivered_shipments']);
    Route::get('/shipments.add_shipment', [ShipmentController::class,'ship_create']);
    Route::get('/shipments.deleted_shipments', [ShipmentController::class,'deleted_shipments']);
    Route::get('/shipment_delete_restore/{id}', [ShipmentController::class,'shipment_delete_restore']);
    Route::get('/shipment_delete_permanent/{id}', [ShipmentController::class,'delete_permanent']);
    Route::get('/shipments.inTransit_shipments', [ShipmentController::class,'inTransit_shipments']);
    Route::post('/shipment_search', [ShipmentController::class,'shipment_search']);
    
    Route::get('export', [ShipmentController::class, 'export'])->name('export');
    Route::post('import', [ShipmentController::class, 'import'])->name('import');

    
    Route::get('/shipments.import_shipments', [ShipmentController::class,'import_shipments']);
    Route::get('/shipments.export_shipments', [ShipmentController::class,'export_shipments']);
    Route::get('/shipment_archive/{id}', [ShipmentController::class,'shipment_archive']);
    Route::get('/shipment_De_archive/{id}', [ShipmentController::class,'shipment_De_archive']);
    Route::get('/shipments.archive_shipments', [ShipmentController::class,'archive_shipments']);

    Route::get('/shipment_delete_from_search/{id}', [ShipmentController::class,'shipment_delete_from_search']);
    Route::get('/shipment_archive_from_search/{id}', [ShipmentController::class,'shipment_archive_from_search']);
    Route::get('/shipments.print_shipments', [ShipmentController::class,'print_shipments']);

    Route::post('/shipments.bulk_print', [ShipmentController::class,'bulk_print']);
    
    
    // mainsettings.applySocialchanges
    // rpo.store

    // RPO_detail
    // ->route('RPO.pendings');
    

});

app/Models/City.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    use HasFactory;
    public $fillable = [
        'name',
        'smsacity',
        'city_code',
        'title',
        'desc',
        'keywords',
        'state_id',
        'country_id'

    ];
    public function state()
    {
        return $this->belongsTo(State::class);
    }

    //R
    public function shipment()
    {
        return $this->belongsTo(shipment::class);
    }

    // public function name()
    // {
    //     return $this->name;
    // }

}

app/Http/Controllers/CityController.php
<?php

namespace App\Http\Controllers;

use App\Models\City;
use App\Models\Country;
use App\Models\State;
use Illuminate\Http\Request;

class CityController extends Controller
{
    public function index()
    {

        $cities = City::all();
        return view('cities.index',compact('cities'));
    }
    public function create()
    {
        $states=State::all();
        $countries=Country::all();
        return view('cities.create',compact('states','countries'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'state_id' => 'required',
            'name'=>'required',
            'smsacity'=>'required',
            'title'=>'required',
            'desc'=>'required',
            'keywords'=>'required',
            'country_id'=>'required',
        ]);

        $city=new City();
        $city->state_id=$request->input('state_id');
        $city->country_id=$request->input('country_id');
        $city->name=$request->input('name');
        $city->smsacity=$request->input('smsacity');
        $city->title=$request->input('title');
        $city->desc=$request->input('desc');
        $city->keywords=$request->input('keywords');


        $city->city_code='CIT'.rand(23,55);
        $city->save();
        return redirect()->route('cities.index')->with('success','Created Successfully.');
    }
    public function edit(City $city)
    {   $states=State::all();
        $countries=Country::all();
        return view('cities.edit',compact('city','states','countries'));
    }


    public function update(Request $request, City $city)
    {
        $request->validate([
            'state_id' => 'required',
            'name'=>'required',
            'smsacity'=>'required',
            'title'=>'required',
            'desc'=>'required',
            'keywords'=>'required',
            'country_id'=>'required',
        ]);
        $city->state_id=$request->input('state_id');
        $city->state_id=$request->input('country_id');
        $city->name=$request->input('name');
        $city->smsacity=$request->input('smsacity');
        $city->title=$request->input('title');
        $city->desc=$request->input('desc');
        $city->keywords=$request->input('keywords');


        $city->city_code='CIT'.rand(23,55);

        $city->update();
        return redirect()->route('cities.index')->with('success','Updated Successfully.');
    }

    public function destroy(City $city)
    {
        $city->delete();
        return redirect()->route('cities.index')->with('success','Student deleted successfully.');
    }


}

resources/views/cities/create.blade.php
@extends('layout.main')

@section('title')
    <title>Add City</title>
@endsection
@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif
@section('content')
<h1 style="text-align: center; font-size:2.4rem; padding-top:20px" >Add City</h1>
<div class="accordion">
    <form action="{{route('cities.store')}}" method="post" enctype="multipart/form-data">
    @csrf
    <div class="mt-3">
        <label for="name" class="form-label">Name</label>
        <input id="name" type="text" name="name" required class="input w-full border mt-2" placeholder="name">
    </div>
    <div class="sm:mt-2">
        <label for="Country_id" class="form-label" >Country</label>
       <select class="input w-full border mt-2" name="country_id" required>
           @foreach ($countries as  $c)
           <option value="{{$c->id}}">{{$c->country_name}}</option>
           @endforeach
    </select>
    </div>

    <div class="sm:mt-2">
        <label for="state" class="form-label" >State</label>
       <select class="input w-full border mt-2" name="state_id" required>
           @foreach ($states as  $state)
           <option value="{{$state->id}}">{{$state->state_name}}</option>
           @endforeach
    </select>
    </div>

    <div class="mt-3">
        <label for="smsacity" class="form-label">SMSA CITY</label>
        <input id="smsacity" type="text" name="smsacity" required class="input w-full border mt-2" placeholder="SMSA CITY">
    </div>


    <div class="mt-3">
        <label for="title" class="form-label">title</label>
        <input id="title" type="text" name="title" required class="input w-full border mt-2" placeholder="title">
    </div>
    <div class="mt-3">
        <label for="desc" class="form-label">desc</label>
        <input id="desc" type="text" name="desc" required class="input w-full border mt-2" placeholder="desc">
    </div>

    <div class="mt-3">
        <label for="keywords" class="form-label">keywords</label>
        <input id="keywords" type="text" name="keywords" required class="input w-full border mt-2" placeholder="keywords">
    </div>

    <button type="submit" class="button bg-theme-1 text-white mt-5">Submit</button>

    </form>
</div>
@endsection

resources/views/cities/edit.blade.php
@extends('layout.main')

@section('title')
    <title>Edit cities</title>
@endsection

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif


@section('content')
<div class="w-full sm:w-auto flex pb-4">

    <a href="{{route('cities.index')}}"   class="button text-white bg-theme-1 shadow-md mr-2"  style="text-align: center; font-size:0.9rem; padding:14px">Back</a>

</div>
<h1 style="text-align: center; font-size:2.4rem; padding-top:20px" >City</h1>
<div class="accordion">
    <form action="{{ route('cities.update',$city->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="mt-3">
            <label for="name" class="form-label">Name</label>
            <input id="name" type="text" value="{{$city->name}}" name="name" required class="input w-full border mt-2" placeholder="name">
        </div>
        <div class="sm:mt-2">
            <label for="Country_id" class="form-label" >State</label>
           <select class="input w-full border mt-2" name="state_id" required>
               @foreach ($states as  $state)
               <option value="{{$state->id}}">{{$country->state_name}}</option>
               @endforeach
        </select>
        </div>

        <div class="mt-3">
            <label for="smsacity" class="form-label">SMSA CITY</label>
            <input id="smsacity" type="text" value="{{$city->smsacity}}" name="smsacity" required class="input w-full border mt-2" placeholder="SMSA CITY">
        </div>


        <div class="mt-3">
            <label for="title" class="form-label">title</label>
            <input id="title" type="text"  value="{{$city->title}}" name="title" required class="input w-full border mt-2" placeholder="title">
        </div>
        <div class="mt-3">
            <label for="desc" class="form-label">desc</label>
            <input id="desc" type="text"  value="{{$city->desc}}" name="desc" required class="input w-full border mt-2" placeholder="desc">
        </div>

        <div class="mt-3">
            <label for="keywords" class="form-label">keywords</label>
            <input id="keywords" type="text" name="keywords"  value="{{$city->keywords}}" required class="input w-full border mt-2" placeholder="keywords">
        </div>


    <button type="submit" class="button bg-theme-1 text-white mt-5">Submit</button>

    </form>
</div>
@endsection

resources/views/cities/index.blade.php
@extends('layout.main')

@section('title')
    <title>cities</title>
@endsection

@section('content')
<h1 style="text-align: center; font-size:2.4rem; padding-top:20px" >cities</h1>



<div class="w-full sm:w-auto flex pb-4">

    <a href="{{route('cities.create')}}"   class="button text-white bg-theme-1 shadow-md mr-2"  style="text-align: center; font-size:0.9rem; padding:14px">Add City</a>

</div>




<div class="overflow-x-auto">
    <table class="table" id="example">
        <thead>
            <tr class="bg-gray-700 dark:bg-dark-1 text-white">
                 <th class="whitespace-nowrap">#</th>
                 <th class="whitespace-nowrap">Name</th>
                 <th class="whitespace-nowrap">SMSA City</th>
                 <th class="whitespace-nowrap">City Code</th>
                 <th class="whitespace-nowrap">title</th>
                 <th class="whitespace-nowrap">Description</th>
                 <th class="whitespace-nowrap">keywords</th>

                 <th class="whitespace-nowrap">Action</th>

            </tr>
        </thead>
        <tbody>
            @foreach ( $cities as $c  )
            <tr>
                <td>{{$c->id}}</td>
                <td>{{$c->name}}</td>
                <td>{{$c->smsacity}}</td>
                <td>{{$c->city_code}}</td>
                <td>{{$c->title}}</td>
                <td>{{$c->desc}}</td>
                <td>{{$c->keywords}}</td>

                <td>
                    <form action="{{ route('cities.destroy',$c->id) }}" method="POST">
                        <a class="button w-24 mr-1 mb-2 bg-theme-9 text-white "  href="{{ route('cities.edit',$c->id) }}" >Edit</a>
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="button w-24 mr-1 mb-2 bg-theme-6 text-white">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
            {{-- dark:bg-dark-1  --}}
        </tbody>
    </table>


</div>

@endsection